"""Curated paper records used to build the reader-facing database."""

from scripts.models import Survey

SURVEY: Survey = {'updated_on': '2026-09-11',
 'paper': {'title': 'Simulation for Planetary Robotic Perception and Autonomy: A Concise Survey of Recent '
                    'Capabilities and Gaps',
           'source_locator': 'Table I (p. 4), Sections III–V, and the paper bibliography',
           'work_count': 22,
           'original_search_databases': None,
           'original_search_queries': None,
           'original_search_cutoff': None,
           'original_screening_log': None,
           'original_resource_check_dates': None},
 'works': [{'id': 'Giubilato2020',
            'name': 'Giubilato et al.',
            'year': 2020,
            'domain': 'Mars',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'Gazebo',
            'ros': 'R1',
            'access_as_reported': 'Direct',
            'terrain': 'Real',
            'sensors': 'St Cam, 3D LiDAR, IMU',
            'bibliography': {'title': 'Simulation Framework for Mobile Robots in Planetary-Like Environments',
                             'author': 'Giubilato, Riccardo and others',
                             'year': '2020',
                             'doi': '10.1109/MetroAeroSpace48742.2020.9160154',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2020 IEEE 7th International Workshop on Metrology for AeroSpace '
                                          '(MetroAeroSpace)'},
            'publication_url': 'https://doi.org/10.1109/MetroAeroSpace48742.2020.9160154',
            'resource_url': 'https://github.com/MorpheusPD/MarsSim',
            'resource_type': 'Repository',
            'paper_reference': 23,
            'evidence': 'Survey Table I, p. 4; bibliography reference [23]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'Toupet2020ENavSim',
            'name': 'Toupet et al.',
            'year': 2020,
            'domain': 'Mars',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'ROS-based',
            'ros': 'R1',
            'access_as_reported': 'No release listed',
            'terrain': 'Simulated',
            'sensors': 'St Cam, rover state',
            'bibliography': {'title': 'A ROS-based Simulator for Testing the Enhanced Autonomous Navigation '
                                      'of the Mars 2020 Rover',
                             'author': 'Toupet, Olivier and others',
                             'year': '2020',
                             'doi': '10.1109/AERO47225.2020.9172345',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2020 IEEE Aerospace Conference'},
            'publication_url': 'https://doi.org/10.1109/AERO47225.2020.9172345',
            'resource_url': None,
            'resource_type': None,
            'paper_reference': 27,
            'evidence': 'Survey Table I, p. 4; bibliography reference [27]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'Mueller2021',
            'name': 'OAISYS',
            'year': 2021,
            'domain': 'Planet.',
            'category': 'Multi-platform',
            'platform_group': 'Multi-platform',
            'engine': 'Blender',
            'ros': None,
            'access_as_reported': 'Direct',
            'terrain': 'Synthetic',
            'sensors': 'RGB-D (extensible)',
            'bibliography': {'title': 'A Photorealistic Terrain Simulation Pipeline for Unstructured Outdoor '
                                      'Environments',
                             'author': 'Müller, M. G. and others',
                             'year': '2021',
                             'doi': '10.1109/IROS51168.2021.9636644',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2021 IEEE/RSJ International Conference on Intelligent Robots and '
                                          'Systems (IROS)'},
            'publication_url': 'https://doi.org/10.1109/IROS51168.2021.9636644',
            'resource_url': 'https://github.com/DLR-RM/oaisys',
            'resource_type': 'Repository',
            'paper_reference': 8,
            'evidence': 'Survey Table I, p. 4; bibliography reference [8]. Capabilities are transcribed from '
                        'the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'MarsSim2023',
            'name': 'MarsSim',
            'year': 2023,
            'domain': 'Mars',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'Gazebo',
            'ros': 'R1',
            'access_as_reported': 'No release listed',
            'terrain': 'Real',
            'sensors': 'Mastcam',
            'bibliography': {'title': 'MarsSim: A High-Fidelity Physical and Visual Simulation for Mars '
                                      'Rovers',
                             'author': 'Zhou, Ruyi and others',
                             'year': '2023',
                             'doi': '10.1109/TAES.2022.3207705',
                             'eprint': None,
                             'journal': 'IEEE Transactions on Aerospace and Electronic Systems',
                             'booktitle': None},
            'publication_url': 'https://doi.org/10.1109/TAES.2022.3207705',
            'resource_url': None,
            'resource_type': None,
            'paper_reference': 24,
            'evidence': 'Survey Table I, p. 4; bibliography reference [24]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': 'The year follows Table I and the survey’s bibliography (2023). The DOI registry '
                    'currently lists 2022.'},
           {'id': 'Cloud2023',
            'name': 'SEELO',
            'year': 2023,
            'domain': 'Lunar',
            'category': 'Excavator',
            'platform_group': 'Construction',
            'engine': 'Unity',
            'ros': None,
            'access_as_reported': 'No release listed',
            'terrain': 'Real',
            'sensors': 'Vision, IMU',
            'bibliography': {'title': 'Lunar Excavator Mission Operations Using Dynamic Movement Primitives',
                             'author': 'Cloud, Joseph M. and others',
                             'year': '2023',
                             'doi': '10.1109/IROS55552.2023.10342005',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2023 IEEE/RSJ International Conference on Intelligent Robots and '
                                          'Systems (IROS)'},
            'publication_url': 'https://doi.org/10.1109/IROS55552.2023.10342005',
            'resource_url': None,
            'resource_type': None,
            'paper_reference': 10,
            'evidence': 'Survey Table I, p. 4; bibliography reference [10]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'LunarSim2023',
            'name': 'LunarSim',
            'year': 2023,
            'domain': 'Lunar',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'Unity',
            'ros': 'R2',
            'access_as_reported': 'Direct',
            'terrain': 'Synthetic',
            'sensors': 'RGB-D, IMU',
            'bibliography': {'title': 'LunarSim: Lunar Rover Simulator Focused on High Visual Fidelity and '
                                      'ROS 2 Integration for Advanced Computer Vision Algorithm Development',
                             'author': 'Pieczyński, Dominik and others',
                             'year': '2023',
                             'doi': '10.3390/app132212401',
                             'eprint': None,
                             'journal': 'Applied Sciences',
                             'booktitle': None},
            'publication_url': 'https://doi.org/10.3390/app132212401',
            'resource_url': 'https://github.com/PUTvision/LunarSim',
            'resource_type': 'Repository',
            'paper_reference': 13,
            'evidence': 'Survey Table I, p. 4; bibliography reference [13]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'Yunn2023',
            'name': 'Jiang et al.',
            'year': 2023,
            'domain': 'Mars',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'Blender',
            'ros': None,
            'access_as_reported': 'No release listed',
            'terrain': 'Synthetic',
            'sensors': 'RGB-D + Sem',
            'bibliography': {'title': 'A Mars Multi-terrain Simulator Using a Modular Terrain Construction '
                                      'Framework',
                             'author': 'Jiang, Yun and others',
                             'year': '2023',
                             'doi': '10.1109/ONCON60463.2023.10431105',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2023 IEEE 2nd Industrial Electronics Society Annual On-Line '
                                          'Conference (ONCON)'},
            'publication_url': 'https://doi.org/10.1109/ONCON60463.2023.10431105',
            'resource_url': None,
            'resource_type': None,
            'paper_reference': 28,
            'evidence': 'Survey Table I, p. 4; bibliography reference [28]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'DUST2023',
            'name': 'DUST',
            'year': 2023,
            'domain': 'Lunar',
            'category': 'Rover-relevant',
            'platform_group': 'Rover-relevant',
            'engine': 'Unreal Engine',
            'ros': None,
            'access_as_reported': 'Request',
            'terrain': 'Real/DEM',
            'sensors': 'Rendered terrain views',
            'bibliography': {'title': 'Digital Lunar Exploration Sites Unreal Simulation Tool (DUST)',
                             'author': 'Bingham, Lee and others',
                             'year': '2023',
                             'doi': '10.1109/AERO55745.2023.10115607',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2023 IEEE Aerospace Conference'},
            'publication_url': 'https://doi.org/10.1109/AERO55745.2023.10115607',
            'resource_url': 'https://software.nasa.gov/software/MSC-27522-1',
            'resource_type': 'Request portal',
            'paper_reference': 16,
            'evidence': 'Survey Table I, p. 4; bibliography reference [16]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'Richard_2024',
            'name': 'OmniLRS',
            'year': 2024,
            'domain': 'Lunar',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'Isaac Sim',
            'ros': 'R1/R2',
            'access_as_reported': 'Direct',
            'terrain': 'Real + proc.',
            'sensors': 'RGB-D, 2D/3D LiDAR, IMU',
            'bibliography': {'title': 'OmniLRS: A Photorealistic Simulator for Lunar Robotics',
                             'author': 'Richard, Antoine and others',
                             'year': '2024',
                             'doi': '10.1109/ICRA57147.2024.10610026',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2024 IEEE International Conference on Robotics and Automation '
                                          '(ICRA)'},
            'publication_url': 'https://doi.org/10.1109/ICRA57147.2024.10610026',
            'resource_url': 'https://github.com/OmniLRS/OmniLRS',
            'resource_type': 'Repository',
            'paper_reference': 9,
            'evidence': 'Survey Table I, p. 4; bibliography reference [9]. Capabilities are transcribed from '
                        'the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'MarsDrone2024',
            'name': 'MarsDrone',
            'year': 2024,
            'domain': 'Mars',
            'category': 'Aerial',
            'platform_group': 'Aerial',
            'engine': 'Unreal Engine',
            'ros': None,
            'access_as_reported': 'No release listed',
            'terrain': 'Real',
            'sensors': 'Cam, Alt, Inc, IMU',
            'bibliography': {'title': 'MarsDrone: A Next-Generation Simulation System for Mars Unmanned '
                                      'Aerial Vehicles',
                             'author': 'Zhang, Guoxing and Li, Qiuping',
                             'year': '2024',
                             'doi': '10.1109/AERO58975.2024.10521330',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2024 IEEE Aerospace Conference'},
            'publication_url': 'https://doi.org/10.1109/AERO58975.2024.10521330',
            'resource_url': None,
            'resource_type': None,
            'paper_reference': 25,
            'evidence': 'Survey Table I, p. 4; bibliography reference [25]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'RLRoverLAB2024',
            'name': 'RLRoverLab',
            'year': 2024,
            'domain': 'Lu./Ma.',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'Isaac Sim',
            'ros': None,
            'access_as_reported': 'Direct',
            'terrain': 'Synthetic',
            'sensors': 'RGB Cam',
            'bibliography': {'title': 'RLRoverLAB: An Advanced Reinforcement Learning Suite for Planetary '
                                      'Rover Simulation and Training',
                             'author': 'Mortensen, Anton Bjørndahl and Bøgh, Simon',
                             'year': '2024',
                             'doi': '10.1109/iSpaRo60631.2024.10687686',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2024 International Conference on Space Robotics (iSpaRo)'},
            'publication_url': 'https://doi.org/10.1109/iSpaRo60631.2024.10687686',
            'resource_url': 'https://github.com/abmoRobotics/RLRoverLab',
            'resource_type': 'Repository',
            'paper_reference': 20,
            'evidence': 'Survey Table I, p. 4; bibliography reference [20]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'LunarRoverSim2024',
            'name': 'LunarRoverSim',
            'year': 2024,
            'domain': 'Lunar',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'PyBullet',
            'ros': None,
            'access_as_reported': 'Direct',
            'terrain': 'Config. lunar',
            'sensors': 'RGB-D + Seg',
            'bibliography': {'title': 'Development of a Lunar Rover Simulator with an Interface for '
                                      'Reinforcement Learning',
                             'author': 'Khunmaturod, Assawayut and Chang, Dong',
                             'year': '2024',
                             'doi': '10.1109/CACRE62362.2024.10634867',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2024 9th International Conference on Automation, Control and '
                                          'Robotics Engineering (CACRE)'},
            'publication_url': 'https://doi.org/10.1109/CACRE62362.2024.10634867',
            'resource_url': 'https://github.com/assawayut/LunarRoverSim',
            'resource_type': 'Repository',
            'paper_reference': 17,
            'evidence': 'Survey Table I, p. 4; bibliography reference [17]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': 'The conference name, omitted from the survey bibliography, was verified against the '
                    'publisher’s bibliographic record.'},
           {'id': 'ISMRS2024',
            'name': 'ISMRS',
            'year': 2024,
            'domain': 'Mars',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'Isaac Sim',
            'ros': 'R2',
            'access_as_reported': 'No release listed',
            'terrain': 'Real',
            'sensors': 'St Cam, IMU, LiDAR, Enc',
            'bibliography': {'title': 'High fidelity Mars Rover simulation platform based on digital twin '
                                      'and machine learning integration: Innovation and application of ISMRS',
                             'author': 'Wan, Gang and others',
                             'year': '2024',
                             'doi': '10.21203/rs.3.rs-4851864/v1',
                             'eprint': None,
                             'journal': None,
                             'booktitle': None},
            'publication_url': 'https://doi.org/10.21203/rs.3.rs-4851864/v1',
            'resource_url': None,
            'resource_type': None,
            'paper_reference': 29,
            'evidence': 'Survey Table I, p. 4; bibliography reference [29]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'GUISS2024',
            'name': 'GUISS',
            'year': 2024,
            'domain': 'Icy moon',
            'category': 'Rover-relevant',
            'platform_group': 'Rover-relevant',
            'engine': 'Blender-based',
            'ros': None,
            'access_as_reported': 'Direct',
            'terrain': 'Synthetic',
            'sensors': 'Stereo imagery',
            'bibliography': {'title': 'Icy Moon Surface Simulation and Stereo Depth Estimation for Sampling '
                                      'Autonomy',
                             'author': 'Bhaskara, Ramchander and others',
                             'year': '2024',
                             'doi': '10.1109/aero58975.2024.10521439',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2024 IEEE Aerospace Conference'},
            'publication_url': 'https://doi.org/10.1109/aero58975.2024.10521439',
            'resource_url': 'https://github.com/nasa-jpl/guiss',
            'resource_type': 'Repository',
            'paper_reference': 21,
            'evidence': 'Survey Table I, p. 4; bibliography reference [21]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'Chrono2024',
            'name': 'Batagoda et al.',
            'year': 2025,
            'domain': 'Lunar',
            'category': 'Excavator',
            'platform_group': 'Construction',
            'engine': 'Chrono',
            'ros': 'R2',
            'access_as_reported': 'Direct',
            'terrain': 'Real (Earth)',
            'sensors': 'Cam, sensor sim.',
            'bibliography': {'title': 'A Physics-Based Sensor Simulation Environment for Lunar Ground '
                                      'Operations',
                             'author': 'Batagoda, Nevindu M. and others',
                             'year': '2025',
                             'doi': '10.1109/AERO63441.2025.11068496',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2025 IEEE Aerospace Conference'},
            'publication_url': 'https://doi.org/10.1109/AERO63441.2025.11068496',
            'resource_url': 'https://github.com/projectchrono/chrono',
            'resource_type': 'Engine repository',
            'paper_reference': 14,
            'evidence': 'Survey Table I, p. 4; bibliography reference [14]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': 'The linked repository is the public Chrono engine basis; it does not establish release '
                    'of the study-specific experiments.'},
           {'id': 'LuSeg2025',
            'name': 'LuSeg/LESS',
            'year': 2025,
            'domain': 'Lunar',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'UE + AirSim',
            'ros': 'R1/R2',
            'access_as_reported': 'Direct',
            'terrain': None,
            'sensors': 'RGB-D + Seg',
            'bibliography': {'title': 'LuSeg: Efficient Negative and Positive Obstacles Segmentation via '
                                      'Contrast-Driven Multi-Modal Feature Fusion on the Lunar',
                             'author': 'Jiao, Shuaifeng and others',
                             'year': '2025',
                             'doi': '10.1109/IROS60139.2025.11246916',
                             'eprint': None,
                             'journal': None,
                             'booktitle': '2025 IEEE/RSJ International Conference on Intelligent Robots and '
                                          'Systems (IROS)'},
            'publication_url': 'https://doi.org/10.1109/IROS60139.2025.11246916',
            'resource_url': 'https://github.com/nubot-nudt/LuSeg',
            'resource_type': 'Repository',
            'paper_reference': 18,
            'evidence': 'Survey Table I, p. 4; bibliography reference [18]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'Mattias2025',
            'name': 'Linde et al.',
            'year': 2025,
            'domain': 'Lunar',
            'category': 'Exc./Truck',
            'platform_group': 'Construction',
            'engine': 'AGX Dynamics',
            'ros': 'R2',
            'access_as_reported': 'No release listed',
            'terrain': 'Synthetic',
            'sensors': 'Observation sensor',
            'bibliography': {'title': 'A simulation framework for autonomous lunar construction work',
                             'author': 'Mattias Linde and others',
                             'year': '2025',
                             'doi': None,
                             'eprint': '2505.22091',
                             'journal': None,
                             'booktitle': None},
            'publication_url': 'https://arxiv.org/abs/2505.22091',
            'resource_url': None,
            'resource_type': None,
            'paper_reference': 15,
            'evidence': 'Survey Table I, p. 4; bibliography reference [15]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'Daniel2025',
            'name': 'Lindmark et al.',
            'year': 2025,
            'domain': 'Lunar',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'OpenPLX + AGX',
            'ros': 'R2',
            'access_as_reported': 'No release listed',
            'terrain': 'LDEM-derived',
            'sensors': 'RGB-D, LiDAR, IMU',
            'bibliography': {'title': 'An integrated process for design and control of lunar robotics using '
                                      'AI and simulation',
                             'author': 'Daniel Lindmark and others',
                             'year': '2025',
                             'doi': None,
                             'eprint': '2509.12367',
                             'journal': None,
                             'booktitle': None},
            'publication_url': 'https://arxiv.org/abs/2509.12367',
            'resource_url': None,
            'resource_type': None,
            'paper_reference': 11,
            'evidence': 'Survey Table I, p. 4; bibliography reference [11]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'PlanetaryPathBench2025',
            'name': 'PlanetaryPathBench',
            'year': 2025,
            'domain': 'Ma./Lu.',
            'category': 'Rover-relevant',
            'platform_group': 'Rover-relevant',
            'engine': 'Benchmark maps',
            'ros': None,
            'access_as_reported': 'Direct',
            'terrain': 'Real/DEM',
            'sensors': 'Occupancy maps',
            'bibliography': {'title': 'Planetary Terrain Datasets and Benchmarks for Rover Path Planning',
                             'author': 'Marvin Chancán and others',
                             'year': '2025',
                             'doi': None,
                             'eprint': '2512.21438',
                             'journal': None,
                             'booktitle': None},
            'publication_url': 'https://arxiv.org/abs/2512.21438',
            'resource_url': 'https://github.com/mchancan/PlanetaryPathBench',
            'resource_type': 'Repository',
            'paper_reference': 22,
            'evidence': 'Survey Table I, p. 4; bibliography reference [22]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'MARTIAN2026',
            'name': 'MARTIAN',
            'year': 2026,
            'domain': 'Mars',
            'category': 'Aerial',
            'platform_group': 'Aerial',
            'engine': 'Blender',
            'ros': None,
            'access_as_reported': 'Direct',
            'terrain': 'Real map',
            'sensors': 'Aerial RGB + pose',
            'bibliography': {'title': 'MARTIAN: A Rendering Framework for Aerial Mars Imagery from HiRISE '
                                      'Orbital Data',
                             'author': 'Dario Pisanti and Georgios Georgakis',
                             'year': '2026',
                             'doi': None,
                             'eprint': '2605.29647',
                             'journal': None,
                             'booktitle': None},
            'publication_url': 'https://arxiv.org/abs/2605.29647',
            'resource_url': 'https://github.com/nasa-jpl/martian',
            'resource_type': 'Repository',
            'paper_reference': 26,
            'evidence': 'Survey Table I, p. 4; bibliography reference [26]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'POLARSim2026',
            'name': 'POLAR-Sim',
            'year': 2026,
            'domain': 'Lunar',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'Chrono',
            'ros': None,
            'access_as_reported': 'Direct',
            'terrain': 'Real + synth.',
            'sensors': 'RGB, annotations, terrain meshes',
            'bibliography': {'title': "POLAR-Sim: Augmenting NASA's POLAR Dataset for Data-Driven Lunar "
                                      'Perception and Rover Simulation',
                             'author': 'Chen, Bo-Hsun and others',
                             'year': '2026',
                             'doi': '10.1109/MAES.2025.3617426',
                             'eprint': None,
                             'journal': 'IEEE Aerospace and Electronic Systems Magazine',
                             'booktitle': None},
            'publication_url': 'https://doi.org/10.1109/MAES.2025.3617426',
            'resource_url': 'https://github.com/uwsbel/POLAR-Sim',
            'resource_type': 'Repository',
            'paper_reference': 12,
            'evidence': 'Survey Table I, p. 4; bibliography reference [12]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': ''},
           {'id': 'DualSim2026',
            'name': 'Kurt et al.',
            'year': 2026,
            'domain': 'Lunar',
            'category': 'Rover',
            'platform_group': 'Rover-relevant',
            'engine': 'MuJoCo + Isaac',
            'ros': None,
            'access_as_reported': 'No release listed',
            'terrain': 'Synthetic',
            'sensors': 'RGB-D + pose',
            'bibliography': {'title': 'A Dual-Simulator Framework for Physics Based Locomotion and Vision '
                                      'Based Navigation of Planetary Rovers',
                             'author': 'Umut Kurt and others',
                             'year': '2026',
                             'doi': None,
                             'eprint': None,
                             'journal': None,
                             'booktitle': 'Workshop on Intelligent Space Robotics and Systems'},
            'publication_url': 'https://openreview.net/pdf?id=YdtCNcDCIV',
            'resource_url': None,
            'resource_type': None,
            'paper_reference': 19,
            'evidence': 'Survey Table I, p. 4; bibliography reference [19]. Capabilities are transcribed '
                        'from the survey, not independently benchmarked.',
            'note': 'The scholarly-source link was located in the ICRA 2026 Space Robotics Workshop program '
                    'during the companion review. The paper’s study-artifact access classification is '
                    'preserved.'}],
 'additional_works': [{'id': 'SRB2025',
                       'name': 'Space Robotics Bench (SRB)',
                       'year': 2025,
                       'title': 'Space Robotics Bench: Robot Learning Beyond Earth',
                       'status': 'Additional related framework',
                       'publication_url': 'https://arxiv.org/abs/2509.23328',
                       'resource_url': 'https://github.com/AndrejOrsula/space_robotics_bench',
                       'basis': 'SRB paper, Sections III-C, III-D and IV; Table II.',
                       'scope_note': 'SRB covers planetary and orbital robotics, including surface '
                                     'navigation and manipulation as well as spacecraft tasks. Its planetary '
                                     'capabilities are relevant to this survey. Orbital coverage alone does '
                                     'not make the entire framework out of scope.',
                       'decision_note': 'Documented here as an additional related framework. This companion '
                                        'update preserves the 22-work dataset analyzed in the accepted '
                                        'paper; SRB is not added to its counts.',
                       'historical_reason': None,
                       'reviewed_on': '2026-09-11'},
                      {'id': 'Junnosuke2024',
                       'name': 'Kamohara et al.',
                       'year': 2024,
                       'title': 'Modeling of Terrain Deformation by a Grouser Wheel for Lunar Rover '
                                'Simulation',
                       'status': 'Cited outside the core dataset',
                       'publication_url': 'https://arxiv.org/abs/2408.13468',
                       'resource_url': None,
                       'basis': 'Survey Section III-E, p. 5.',
                       'scope_note': 'Related research on terrain deformation or terramechanics for lunar '
                                     'rover simulation.',
                       'decision_note': 'Section III-E explicitly discusses this work outside the core set. '
                                        'This page preserves that distinction; it does not infer a more '
                                        'specific original exclusion reason.',
                       'historical_reason': None,
                       'reviewed_on': '2026-09-11'},
                      {'id': 'Jakob2026',
                       'name': 'Kern et al.',
                       'year': 2025,
                       'title': 'Data-Driven Terramechanics Approach Towards a Realistic Real-Time Simulator '
                                'for Lunar Rovers',
                       'status': 'Cited outside the core dataset',
                       'publication_url': 'https://doi.org/10.1109/iSpaRo66239.2025.11436587',
                       'resource_url': None,
                       'basis': 'Survey Section III-E, p. 5.',
                       'scope_note': 'Related research on terrain deformation or terramechanics for lunar '
                                     'rover simulation.',
                       'decision_note': 'Section III-E explicitly discusses this work outside the core set. '
                                        'This page preserves that distinction; it does not infer a more '
                                        'specific original exclusion reason.',
                       'historical_reason': None,
                       'reviewed_on': '2026-09-11'}]}
